FROM node:20-alpine as build-frontend
WORKDIR /src
COPY frontend/package*.json frontend/ /src/
RUN npm ci
COPY frontend/ /src/
ENV VITE_API_URL=/api
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-frontend /src/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

