version: "3.9"

services:
  web:
    build: .
    container_name: jobboard_web
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.wsgi:app
      - FLASK_ENV=development
      - SECRET_KEY=change-me
      - JWT_SECRET_KEY=change-me
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: jobboard_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}