version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: jz/flask_live:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.routes.py
      - FLASK_ENV=development
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres  # ✅ Fixed key
      - SECRET_KEY=sOmeSecreTKey1!
      - UPLOAD_FOLDER='static/resumes'
      - MAIL_SERVER='smtp.gmail.com'
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}  # ✅ Fixed indentation and removed "-"